var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "tue": "mar",
            "wed": "mie",
            "thu": "jue",
            "fri": "vie",
            "sat": "sab",
            "jan": "Jan",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic",
			"mon": "lun"
        },
        "no_implemented": "Sin implementar",
        "to_date_view": "Clic para ver los eventos de este día",
        "i_undefined": "Indefinido",
        "allday_event": "Todos los eventos del día",
        "repeat_event": "Repetir Evento",
        "time": "Fecha",
        "event": "Asunto",
        "location": "Observaciones",
        "participant": "Participantes",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nuevo evento",
        "confirm_delete_event": "¿Confirma que desea eliminar este evento? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "El asunto no puede ser vacío",
        "view_no_ready": "La vista no está lista",
        "example": "Ejm. Visita al cliente...",
        "content": "Asunto",
        "create_event": "Crear evento",
        "update_detail": "Más detallado",
        "click_to_detail": "Ver detalles",
        "i_delete": "Eliminar",
        "day_plural": "días",
        "others": "Otros",
        "item": ""
    }
});
